server:
  port: 8086

spring:
  application:
    name: checkout-service
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
      config:
        server-addr: localhost:8848
        file-extension: yaml
  config:
    import: optional:nacos:${spring.application.name}.${spring.cloud.nacos.config.file-extension}

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://rm-bp1x6y6u8589d251tto.mysql.rds.aliyuncs.com:3306/shop_db?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: shop_user
    password: efEwiuofbw!!
    type: com.alibaba.druid.pool.DruidDataSource

dubbo:
  application:
    name: ${spring.application.name}
  protocol:
    name: dubbo
    port: -1
  registry:
    address: nacos://localhost:8848
  consumer:
    check: false
    timeout: 3000
    version: 1.0.0