server:
  port: 8087

spring:
  application:
    name: payment-service
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
      config:
        server-addr: localhost:8848
        file-extension: yaml
  config:
    import: optional:nacos:${spring.application.name}.${spring.cloud.nacos.config.file-extension}

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://rm-bp1x6y6u8589d251tto.mysql.rds.aliyuncs.com:3306/shop_db?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: shop_user
    password: efEwiuofbw!!
    type: com.alibaba.druid.pool.DruidDataSource

dubbo:
  application:
    name: payment-service
  protocol:
    name: dubbo
    port: 20891
  registry:
    address: nacos://localhost:8848
  provider:
    timeout: 3000
    version: 1.0.0
  scan:
    base-packages: com.shop.payment.service

# MyBatis Plus配置
mybatis-plus:
  type-aliases-package: com.shop.payment.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0