server:
  port: 8083

spring:
  application:
    name: product-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/mall_product
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
      config:
        server-addr: localhost:8848
        file-extension: yaml

dubbo:
  application:
    name: ${spring.application.name}
  protocol:
    name: dubbo
    port: -1
  registry:
    address: nacos://localhost:8848 